export const Fonts = {
    black_italic: 'Montserrat-BlackItalic',
    black: 'Montserrat-Black',
    extra_bold_italic: 'Montserrat-ExtraBoldItalic',
    extra_bold: 'Montserrat-ExtraBold',
    bold_italic: 'Montserrat-BoldItalic',
    bold: 'Montserrat-Bold',
    semi_bold_italic: 'Montserrat-SemiBoldItalic',
    semi_bold: 'Montserrat-SemiBold',
    medium_italic: 'Montserrat-MediumItalic',
    medium: 'Montserrat-Medium',
    italic: 'Montserrat-Italic',
    regular: 'Montserrat-Regular',
    light_italic: 'Montserrat-LightItalic',
    light: 'Montserrat-Light',
    extra_light_italic: 'Montserrat-ExtraLightItalic',
    extra_light: 'Montserrat-ExtraLight',
    thin_italic: 'Montserrat-ThinItalic',
    thin: 'Montserrat-Thin',
}